### ISSUE TITLE
Build Failure using JDK 11

### ISSUE THREAD

**Issue by aquamme** [lagom/lagom-java-maven-chirper-example#25]
I get the following error when following the instructions in the readme.  Any ideas?

```
Downloaded from central: https://repo.maven.apache.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.5/akka-http-core_2.12-10.1.5.jar (3.5 MB at 686 kB/s)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/aaron/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-12-22T17:57:42.253Z [info] akka.event.slf4j.Slf4jLogger [] - Slf4jLogger started
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for lagom-java-chirper 1.0.0-SNAPSHOT:
[INFO] 
[INFO] lagom-java-chirper ................................. FAILURE [ 27.930 s]
[INFO] friend-api ......................................... SKIPPED
[INFO] friend-impl ........................................ SKIPPED
[INFO] chirp-api .......................................... SKIPPED
[INFO] chirp-impl ......................................... SKIPPED
[INFO] activity-stream-api ................................ SKIPPED
[INFO] activity-stream-impl ............................... SKIPPED
[INFO] load-test-api ...................................... SKIPPED
[INFO] load-test-impl ..................................... SKIPPED
[INFO] front-end .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.647 s
[INFO] Finished at: 2018-12-22T11:57:42-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.lightbend.lagom:lagom-maven-plugin:1.5.0-RC1:runAll (default-cli) on project lagom-java-chirper: Execution lagom-internal-request of goal com.lightbend.lagom:lagom-maven-plugin:1.5.0-RC1:startServiceLocator failed: Failed to start embedded Service Locator or Service Gateway. Hint: Are ports 9008 or 9000 already in use?: Unable to create injector, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, java.lang.reflect.UndeclaredThrowableException
[ERROR]   at com.lightbend.lagom.javadsl.server.ServiceGuiceSupport$LagomServiceBuilder.bind(ServiceGuiceSupport.java:142) (via modules: com.google.inject.util.Modules$OverrideModule -> com.lightbend.lagom.registry.impl.ServiceRegistryModule)
[ERROR]   while locating com.lightbend.lagom.javadsl.api.ServiceInfo
[ERROR]     for the 3rd parameter of com.lightbend.lagom.internal.javadsl.client.JavadslServiceClientImplementor.<init>(JavadslServiceClientImplementor.scala:37)
[ERROR]   at com.lightbend.lagom.internal.javadsl.client.ServiceClientModule.bindings(ServiceClientModule.scala:13):
[ERROR] Binding(class com.lightbend.lagom.internal.javadsl.client.JavadslServiceClientImplementor to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
[ERROR]   while locating com.lightbend.lagom.internal.javadsl.client.JavadslServiceClientImplementor
[ERROR]     for the 4th parameter of com.lightbend.lagom.internal.javadsl.client.ServiceClientLoader.<init>(ServiceClientLoader.scala:15)
[ERROR]   at com.lightbend.lagom.internal.javadsl.client.ServiceClientModule.bindings(ServiceClientModule.scala:14):
[ERROR] Binding(class com.lightbend.lagom.internal.javadsl.client.ServiceClientLoader to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
[ERROR]   while locating com.lightbend.lagom.internal.javadsl.client.ServiceClientLoader
[ERROR]     for field at com.lightbend.lagom.internal.javadsl.client.ServiceClientProvider.loader(ServiceClientLoader.scala:36)
[ERROR]   at com.lightbend.lagom.javadsl.client.ServiceClientGuiceSupport.bindClient(ServiceClientGuiceSupport.java:28) (via modules: com.google.inject.util.Modules$OverrideModule -> com.lightbend.lagom.registry.impl.ServiceRegistryModule)
[ERROR] 
[ERROR] 1 error: access to public member failed: com.lightbend.lagom.internal.javadsl.registry.ServiceRegistry.descriptor[Ljava.lang.Object;@4700064f/invokeSpecial, from com.lightbend.lagom.internal.javadsl.registry.ServiceRegistry/2 (unnamed module @4cd6f08b)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Java version
```
~/p/m/s/lagom-java-maven-chirper-example (master=) java --version
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

Maven Version
```
~/p/m/s/lagom-java-maven-chirper-example (master=) mvn --version
Apache Maven 3.6.0 (NON-CANONICAL_2018-11-06T03:14:22+01:00_root; 2018-11-05T20:14:22-06:00)
Maven home: /opt/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-jdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.8-arch1-1-arch", arch: "amd64", family: "unix"
```

**Comment by aquamme** [comment]
Downgrading to Java 8 solved the problem. Looks like there isn't official support for Java 11 yet: https://github.com/lagom/lagom/issues/1417

**Comment by TimMoore** [comment]
@aquamme that's correct. Java 8 is required at this time.
